# Generated by Django 4.2 on 2023-04-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sabor', models.CharField(max_length=200)),
                ('ingredientes', models.CharField(max_length=200)),
                ('tiempo_coccion', models.TextField()),
                ('instrucciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('deportista', models.CharField(max_length=200)),
                ('atendido_por', models.TextField()),
            ],
        ),
    ]
