# Generated by Django 4.0.4 on 2023-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTerceraEntrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportes',
            name='atendido_por',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deportes',
            name='deporte',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deportes',
            name='deportista',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deportes',
            name='pais',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nutricion',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nutricion',
            name='especialidad',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nutricion',
            name='matricula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutricion',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='receta',
            name='instrucciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='sabor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_coccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
