# Generated by Django 4.0.4 on 2023-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTerceraEntrega', '0002_alter_deportes_atendido_por_alter_deportes_deporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
    ]
